// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommentAddReq struct {
	Vid     string `path:"vid"`
	Content string `json:"content"`
}

type CommentItem struct {
	Id        string   `json:"id"`
	UserId    string   `json:"user_id"`
	VideoId   string   `json:"video_id"`
	Content   string   `json:"content"`
	CreatedAt int64    `json:"created_at"`
	User      UserItem `json:"user"`
}

type CommentListData struct {
	Total    int64         `json:"total"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`
	Comments []CommentItem `json:"comments"`
}

type CommentListReq struct {
	Vid      string `path:"vid"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
}

type CommentListRsp struct {
	Status int             `json:"status"`
	Data   CommentListData `json:"data"`
	Msg    string          `json:"msg,optional"`
	Error  string          `json:"error,optional"`
}

type CommonRsp struct {
	Status int    `json:"status"`
	Msg    string `json:"msg,optional"`
	Error  string `json:"error,optional"`
}

type DelCommentReq struct {
	Vid string `path:"vid"`
	Cid string `path:"cid"`
}

type FavoriteReq struct {
	Vid string `path:"vid"`
}

type RelationReq struct {
	Uid string `path:"uid"`
}

type UserItem struct {
	Id        string `json:"id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	CreatedAt int64  `json:"created_at"`
	Avatar    string `json:"avatar"`
}

type UserListRsp struct {
	Status int        `json:"status"`
	Data   []UserItem `json:"data"`
	Msg    string     `json:"msg,optional"`
	Error  string     `json:"error,optional"`
}

type UserLoginReq struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type UserRegisterReq struct {
	NickName        string `json:"nick_name"`
	UserName        string `json:"user_name"`
	Password        string `json:"password"`
	PasswordConfirm string `json:"password_confirm"`
}

type UserRsp struct {
	Status int      `json:"status"`
	Data   UserItem `json:"data"`
	Msg    string   `json:"msg,optional"`
	Error  string   `json:"error,optional"`
}

type VideoIdReq struct {
	Id string `path:"id"`
}

type VideoItem struct {
	Id            string `json:"id"`
	Title         string `json:"title"`
	Url           string `json:"url"`
	Info          string `json:"info"`
	Cover         string `json:"cover"`
	CommentCount  uint   `json:"comment_count"`
	FavoriteCount uint   `json:"favorite_count"`
	CreatedAt     int64  `json:"created_at"`
}

type VideoListRsp struct {
	Status int         `json:"status"`
	Data   []VideoItem `json:"data"`
	Msg    string      `json:"msg,optional"`
	Error  string      `json:"error,optional"`
}

type VideoRsp struct {
	Status int       `json:"status"`
	Data   VideoItem `json:"data"`
	Msg    string    `json:"msg,optional"`
	Error  string    `json:"error,optional"`
}

type VideoSearchReq struct {
	KeyWord string `form:"key_word"`
}
