// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommentAddReq struct {
	Vid       string `path:"vid"`
	CommentId string `form:"comment_id,optional"`
	Content   string `json:"content"`
}

type CommentItem struct {
	Id            string   `json:"id"`
	UserId        string   `json:"user_id"`
	VideoId       string   `json:"video_id"`
	CommentId     string   `json:"comment_id,omitempty"`
	RootId        string   `json:"root_id,omitempty"`
	Content       string   `json:"content"`
	FavoriteCount uint     `json:"favorite_count"`
	IsDeleted     bool     `json:"is_deleted"`
	CreatedAt     int64    `json:"created_at"`
	User          UserItem `json:"user"`
}

type CommentListData struct {
	Total    int64         `json:"total"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`
	Comments []CommentItem `json:"comments"`
}

type CommentListReq struct {
	Vid       string `path:"vid"`
	CommentId string `form:"comment_id,optional"`
	Page      int    `form:"page,optional"`
	PageSize  int    `form:"page_size,optional"`
}

type CommentListRsp struct {
	Status int              `json:"status"`
	Data   *CommentListData `json:"data,omitempty"`
	Msg    string           `json:"msg,omitempty"`
	Error  string           `json:"error,omitempty"`
}

type CommonRsp struct {
	Status int    `json:"status"`
	Msg    string `json:"msg,omitempty"`
	Error  string `json:"error,omitempty"`
}

type DelCommentReq struct {
	Vid string `path:"vid"`
	Cid string `path:"cid"`
}

type Disable2FAItem struct {
	Enabled bool `json:"enabled"`
}

type Disable2FAReq struct {
	Password string `json:"password"`
	Code     string `json:"code"`
}

type Disable2FAResp struct {
	Status int             `json:"status"`
	Data   *Disable2FAItem `json:"data,omitempty"`
	Msg    string          `json:"msg,omitempty"`
	Error  string          `json:"error,omitempty"`
}

type FavoriteReq struct {
	Vid       string `path:"vid"`
	CommentId string `form:"comment_id,optional"`
}

type LoginItem struct {
	Need2FA        bool   `json:"need2fa"`
	ChallengeToken string `json:"challengeToken,omitempty"`
	AccessToken    string `json:"accessToken,omitempty"`
	RefreshToken   string `json:"refreshToken,omitempty"`
}

type RefreshTokenItem struct {
	AccessToken string `json:"accessToken,omitempty"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token,optional"`
}

type RefreshTokenResp struct {
	Status int               `json:"status"`
	Data   *RefreshTokenItem `json:"data,omitempty"`
	Msg    string            `json:"msg,omitempty"`
	Error  string            `json:"error,omitempty"`
}

type RelationReq struct {
	Uid string `path:"uid"`
}

type TotpEnrollConfirmItem struct {
	Enabled bool `json:"enabled"`
}

type TotpEnrollConfirmReq struct {
	Code string `json:"code"`
}

type TotpEnrollConfirmResp struct {
	Status int                    `json:"status"`
	Data   *TotpEnrollConfirmItem `json:"data,omitempty"`
	Msg    string                 `json:"msg,omitempty"`
	Error  string                 `json:"error,omitempty"`
}

type TotpEnrollStartItem struct {
	Issuer        string `json:"issuer"`
	AccountName   string `json:"accountName"`
	OTPAuthURL    string `json:"otpauthUrl"`
	QRCodeDataURL string `json:"qrCodeDataUrl"`
}

type TotpEnrollStartReq struct {
}

type TotpEnrollStartResp struct {
	Status int                  `json:"status"`
	Data   *TotpEnrollStartItem `json:"data,omitempty"`
	Msg    string               `json:"msg,omitempty"`
	Error  string               `json:"error,omitempty"`
}

type TotpVerifyItem struct {
	AccessToken  string `json:"accessToken,omitempty"`
	RefreshToken string `json:"refreshToken,omitempty"`
}

type TotpVerifyReq struct {
	Code string `json:"code"`
}

type TotpVerifyResp struct {
	Status int             `json:"status"`
	Data   *TotpVerifyItem `json:"data,omitempty"`
	Msg    string          `json:"msg,omitempty"`
	Error  string          `json:"error,omitempty"`
}

type UserItem struct {
	Id        string `json:"id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	CreatedAt int64  `json:"created_at"`
	Avatar    string `json:"avatar"`
}

type UserListRsp struct {
	Status int         `json:"status"`
	Data   *[]UserItem `json:"data,omitempty"`
	Msg    string      `json:"msg,omitempty"`
	Error  string      `json:"error,omitempty"`
}

type UserLoginReq struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	Status int        `json:"status"`
	Data   *LoginItem `json:"data,omitempty"`
	Msg    string     `json:"msg,omitempty"`
	Error  string     `json:"error,omitempty"`
}

type UserRegisterReq struct {
	NickName        string `json:"nick_name"`
	UserName        string `json:"user_name"`
	Password        string `json:"password"`
	PasswordConfirm string `json:"password_confirm"`
}

type UserRegisterResp struct {
	Status int       `json:"status"`
	Data   *UserItem `json:"data,omitempty"`
	Msg    string    `json:"msg,omitempty"`
	Error  string    `json:"error,omitempty"`
}

type UserRsp struct {
	Status int       `json:"status"`
	Data   *UserItem `json:"data,omitempty"`
	Msg    string    `json:"msg,omitempty"`
	Error  string    `json:"error,omitempty"`
}

type VideoIdReq struct {
	Id string `path:"id"`
}

type VideoItem struct {
	Id            string `json:"id"`
	Title         string `json:"title"`
	Url           string `json:"url"`
	Info          string `json:"info"`
	Cover         string `json:"cover"`
	CommentCount  uint   `json:"comment_count"`
	FavoriteCount uint   `json:"favorite_count"`
	CreatedAt     int64  `json:"created_at"`
}

type VideoListRsp struct {
	Status int          `json:"status"`
	Data   *[]VideoItem `json:"data,omitempty"`
	Msg    string       `json:"msg,omitempty"`
	Error  string       `json:"error,omitempty"`
}

type VideoRsp struct {
	Status int        `json:"status"`
	Data   *VideoItem `json:"data,omitempty"`
	Msg    string     `json:"msg,omitempty"`
	Error  string     `json:"error,omitempty"`
}

type VideoSearchReq struct {
	KeyWord string `form:"key_word"`
}
