// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	comment "github.com/jhw66/myvideo_lab4/internal/handler/comment"
	common "github.com/jhw66/myvideo_lab4/internal/handler/common"
	favorite "github.com/jhw66/myvideo_lab4/internal/handler/favorite"
	relation "github.com/jhw66/myvideo_lab4/internal/handler/relation"
	totp "github.com/jhw66/myvideo_lab4/internal/handler/totp"
	user "github.com/jhw66/myvideo_lab4/internal/handler/user"
	video "github.com/jhw66/myvideo_lab4/internal/handler/video"
	"github.com/jhw66/myvideo_lab4/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/:vid",
					Handler: comment.CommentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:vid/:cid",
					Handler: comment.DelCommentHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/p/comment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/comment/:vid",
				Handler: common.CommentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: common.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/totp/verify",
				Handler: common.TotpVerifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: common.UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: common.UserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/video/rank",
				Handler: common.RankVideosHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/video/:id",
				Handler: common.VideoDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/videos/search",
				Handler: common.VideoSearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/:vid",
					Handler: favorite.FavoriteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/p/favorite"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/favoriteList/me",
					Handler: favorite.FavoriteListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/p"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/:uid",
					Handler: relation.RelationActionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/follower",
					Handler: relation.FollowerListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/following",
					Handler: relation.FollowingListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/friend",
					Handler: relation.FriendListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/p/relation"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/disable",
					Handler: totp.TotpDisableHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/enroll/confirm",
					Handler: totp.TotpEnrollConfirmHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/enroll/start",
					Handler: totp.TotpEnrollStartHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/p/totp"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/avatar",
					Handler: user.UserAvatarHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: user.UserLogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/me",
					Handler: user.UserMeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/p/user"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AccessAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: video.UploadVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: video.UpdateVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: video.DeleteVideoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/me",
					Handler: video.MyVideoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/p/video"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:name",
				Handler: staticFileHandler("static/video"),
			},
		},
		rest.WithPrefix("/static/video"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:name",
				Handler: staticFileHandler("static/cover"),
			},
		},
		rest.WithPrefix("/static/cover"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:name",
				Handler: staticFileHandler("static/avatar"),
			},
		},
		rest.WithPrefix("/static/avatar"),
	)
}
